services:
  proxy-service:
    container_name: proxy-service-container
    image: proxy-service-image:latest
    build:
      context: ./proxy-service
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      INTERNAL_SERVICE_URL: http://${INTERNAL_SERVICE_CONTAINER_NAME}:8081

  internal-service:
    container_name: ${INTERNAL_SERVICE_CONTAINER_NAME}
    image: internal-service-image:latest
    build:
      context: ./internal-service
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
