#INTERNAL_SERVICE_CONTAINER_NAME comes from .env file. This is the way to define variables inside docker compose file.
#I wanted to parametrize it because docker compose creates for me network and he is putting all services inside of it
#once all services are inside one network they can communicate with each other. to do so as a host i need to pass
# container name of given service

services:
  proxy-service:
    container_name: proxy-service-container
    image: proxy-service-image:latest
    build:
      context: ./proxy-service
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      INTERNAL_SERVICE_URL: http://${INTERNAL_SERVICE_CONTAINER_NAME}:8081

  internal-service:
    container_name: ${INTERNAL_SERVICE_CONTAINER_NAME}
    image: internal-service-image:latest
    build:
      context: ./internal-service
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
